spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 799190179658-i2s336un72aho53uicis4ar2sbmeqp04.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: WTW5YeHIx_2c_0ImOv4q
            client-secret: G5lwyNbfRW
            redirect-url: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: e922df13934a37d0a450a16c7eba0252
            client-secret: 2pcGQsBSiOjQNdLEwvD2ZwbMSFpoEHYH
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id