spring:
  redis:
    host: localhost
    port: 6379
  datasource: # local db
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 콘솔 사용 가능하도록 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: fadfsdfhaduifadshfuiawfjweoigjsdaoigjapfobjafdoigbjafdpbjafdiboajdfoiapfdsjgawghwgnjkzdvnfodivjdafpvjadfpobndzkjfvnafdoijgvdafjbnsdkjvaklvjfdjadfobnfdkjbalfgsfdhshhhhhhhhhsss
  refresh-token-validity-in-seconds: 1209600 # 14일
  access-token-validity-in-seconds: 43200 # 12시간